---
- name: Backup Network Device Configurations
  hosts: all
  gather_facts: no
  vars:
    backup_dir: "/home/wiz0rd/Projects/git/Containerlab/Labs/ansible-6/clab-spine-leaf-topology"
    ansible_user: admin
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  tasks:
    - name: Backup Juniper vJunos configurations
      junipernetworks.junos.junos_command:
        commands: 
          - show configuration
      register: juniper_config
      when: "'juniper_vjunosswitch' in group_names"
      vars:
        ansible_connection: netconf
        ansible_network_os: junos

    - name: Save Juniper configuration to file
      copy:
        content: "{{ juniper_config.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname | regex_replace('clab-spine-leaf-topology-', '') }}/config/backup.conf"
      when: "'juniper_vjunosswitch' in group_names"

    - name: Backup Cisco CSR configurations
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: "backup.conf"
          dir_path: "{{ backup_dir }}/{{ inventory_hostname | regex_replace('clab-spine-leaf-topology-', '') }}/config"
      register: cisco_csr_backup
      when: "'vr-csr' in group_names"
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios

    - name: Backup Cisco NX-OS configurations
      cisco.nxos.nxos_config:
        backup: yes
        backup_options:
          filename: "backup.conf"
          dir_path: "{{ backup_dir }}/{{ inventory_hostname | regex_replace('clab-spine-leaf-topology-', '') }}/config"
      register: cisco_nxos_backup
      when: "'vr-n9kv' in group_names"
      vars:
        ansible_connection: network_cli
        ansible_network_os: nxos

    - name: Display backup status
      debug:
        msg: 
          - "Configuration for {{ inventory_hostname }} has been backed up to {{ backup_dir }}/{{ inventory_hostname | regex_replace('clab-spine-leaf-topology-', '') }}/config/backup.conf"
      when: juniper_config.changed or cisco_csr_backup.changed or cisco_nxos_backup.changed
