---
- name: Backup Network Device Configurations
  hosts: all
  gather_facts: no
  vars:
    backup_dir: "/home/wiz0rd/Projects/git/Containerlab/Labs/ansible-6/clab-spine-leaf-topology"
    ansible_user: admin
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  tasks:

    - name: Backup Juniper vJunos configurations
      junipernetworks.junos.junos_command:
        commands:
          - show configuration
      register: juniper_config
      when: "'juniper_vjunosswitch' in group_names"
      vars:
        ansible_connection: netconf
        ansible_network_os: junos

    - name: Save Juniper configuration to file
      copy:
        content: "{{ juniper_config.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname | regex_replace('clab-spine-leaf-topology-', '') }}/config/backup.conf"
      when: "'juniper_vjunosswitch' in group_names"

    - name: Backup full Cisco CSR running configuration (show running-config all)
      cisco.ios.ios_command:
        commands:
          - show running-config all
      register: cisco_csr_running_backup
      when: "'vr-csr' in group_names"
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios

    - name: Save full Cisco CSR running configuration to file
      copy:
        content: "{{ cisco_csr_running_backup.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname | regex_replace('clab-spine-leaf-topology-', '') }}/config/full_running_backup.conf"
      when: "'vr-csr' in group_names"

    - name: Backup Cisco CSR startup configuration
      cisco.ios.ios_command:
        commands:
          - show startup-config
      register: cisco_csr_startup_backup
      when: "'vr-csr' in group_names"
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios

    - name: Save Cisco CSR startup configuration to file
      copy:
        content: "{{ cisco_csr_startup_backup.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname | regex_replace('clab-spine-leaf-topology-', '') }}/config/startup_backup.conf"
      when: "'vr-csr' in group_names"

    - name: Backup full Cisco NX-OS running configuration (show running-config all)
      cisco.nxos.nxos_command:
        commands:
          - show running-config all
      register: cisco_nxos_running_backup
      when: "'vr-n9kv' in group_names"
      vars:
        ansible_connection: network_cli
        ansible_network_os: nxos

    - name: Save full Cisco NX-OS running configuration to file
      copy:
        content: "{{ cisco_nxos_running_backup.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname | regex_replace('clab-spine-leaf-topology-', '') }}/config/full_running_backup.conf"
      when: "'vr-n9kv' in group_names"

    - name: Backup Cisco NX-OS startup configuration
      cisco.nxos.nxos_command:
        commands:
          - show startup-config
      register: cisco_nxos_startup_backup
      when: "'vr-n9kv' in group_names"
      vars:
        ansible_connection: network_cli
        ansible_network_os: nxos

    - name: Save Cisco NX-OS startup configuration to file
      copy:
        content: "{{ cisco_nxos_startup_backup.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname | regex_replace('clab-spine-leaf-topology-', '') }}/config/startup_backup.conf"
      when: "'vr-n9kv' in group_names"

    - name: Display backup status
      debug:
        msg:
          - "Configuration for {{ inventory_hostname }} has been backed up to {{ backup_dir }}/{{ inventory_hostname | regex_replace('clab-spine-leaf-topology-', '') }}/config/"
      when: cisco_csr_running_backup.changed or cisco_csr_startup_backup.changed or cisco_nxos_running_backup.changed or cisco_nxos_startup_backup.changed
